var customerData = {
  status: "success",
  data: [
    {
      id: 1,
      code: 1029,
      name: "Sunil Rohan",
      email: "se@in.com",
      phone: "12345",
      designation: "developer",
    },
    {
      id: 2,
      code: 1031,
      name: "Nithin Samuel",
      email: "ns@in.com",
      phone: "777777",
      designation: "developer-ui",
    },
    {
      id: 3,
      code: 1032,
      name: "Jeeva Winpray",
      email: "jw@in.com",
      phone: "789456",
      designation: "electrical department",
    },
    {
      id: 4,
      code: 1033,
      name: "Rian Edward Samuel",
      email: "res@in.com",
      phone: "963258",
      designation: "doctor",
    },
    {
      id: 5,
      code: 1034,
      name: "Navin Samuel",
      email: "ns2@in.com",
      phone: "741258",
      designation: "communications",
    },
    {
      id: 6,
      code: 1035,
      name: "Jose Jerrome",
      email: "jj@in.com",
      phone: "852369",
      designation: "buisness",
    },
    {
      id: 7,
      code: 1036,
      name: "Sam Valentine",
      email: "sv@in.com",
      phone: "852147",
      designation: "tester",
    },
    {
      id: 8,
      code: 1037,
      name: "Mohan Prasad",
      email: "mp@in.com",
      phone: "12345",
      designation: "Azure",
    },
    {
      id: 9,
      code: 1038,
      name: "Kutty Prabhu",
      email: "kp@in.com",
      phone: "879654",
      designation: "dot net",
    },
    {
      id: 10,
      code: 1039,
      name: "Sridhar J",
      email: "sj@in.com",
      phone: "123654",
      designation: "ui developer",
    },
    {
      id: 11,
      code: 1040,
      name: "Ezhini",
      email: "ep@in.com",
      phone: "987456",
      designation: "tester",
    },
    {
      id: 12,
      code: 1041,
      name: "Siva",
      email: "sp@in.com",
      phone: "852258",
      designation: "student",
    },
    {
      id: 13,
      code: 1042,
      name: "Jeffy Consha",
      email: "jc@in.com",
      phone: "789321",
      designation: "english department",
    },
    {
      id: 14,
      code: 1043,
      name: "Delince Samuel",
      email: "ds@in.com",
      phone: "915258",
      designation: "agriculture department",
    },
    {
      id: 15,
      code: 1044,
      name: "Xavier Francis",
      email: "xf@in.com",
      phone: "951753",
      designation: "cinema industry",
    },
    {
      id: 16,
      code: 1045,
      name: "Kalpana Xavier",
      email: "kx@in.com",
      phone: "98741",
      designation: "housewife",
    },
    {
      id: 17,
      code: 1046,
      name: "Charles Xavier",
      email: "cx@in.com",
      phone: "951753",
      designation: "professor",
    },
    {
      id: 18,
      code: 1047,
      name: "Bruce Wayne",
      email: "bw@in.com",
      phone: "789654",
      designation: "Batman",
    },
    {
      id: 19,
      code: 1048,
      name: "Logan Howlett",
      email: "lh@in.com",
      phone: "753951",
      designation: "Wolverine",
    },
    {
      id: 20,
      code: 1049,
      name: "Scott Summers",
      email: "sj@in.com",
      phone: "123654",
      designation: "Cyclops",
    },
    {
      id: 21,
      code: 1050,
      name: "Tony Stark",
      email: "ts@in.com",
      phone: "0123654",
      designation: "Iron Man",
    },
    {
      id: 22,
      code: 1051,
      name: "Steve Rodgers",
      email: "sr@in.com",
      phone: "98741",
      designation: "Captain America",
    },
    {
      id: 23,
      code: 1052,
      name: "Bruce Banner",
      email: "bb@in.com",
      phone: "999999",
      designation: "Hulk",
    },
    {
      id: 24,
      code: 1053,
      name: "Natasha Romanoff",
      email: "nr@in.com",
      phone: "987456",
      designation: "Black Widow",
    },
    {
      id: 25,
      code: 1054,
      name: "Thor Odinson",
      email: "to@in.com",
      phone: "98741",
      designation: "Thor",
    },
    {
      id: 25,
      code: 1054,
      name: "Clint Barton",
      email: "cb@in.com",
      phone: "987123",
      designation: "Hawkeye",
    },
  ],
};
// export { customersData };
exports.customerData = customerData;
