#run in local
# docker build --no-cache -t test-image .

FROM node:18
RUN apk add chromium
RUN apk add --no-cache git
ENV CHROME_BIN=/usr/bin/chromium-browser
RUN npm config set strict-ssl false
WORKDIR /home/ui-build
COPY . /home/ui-build
RUN npm install --force && npm cache clean --force
RUN npm run ng build -- --prod --output-path=dist

#Install Nginx...
FROM nginx:stable-alpine
#update permisiions in cae env
RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx
RUN sed -i.bak 's/listen\(.*\)80;/listen 5001;/' /etc/nginx/conf.d/default.conf
EXPOSE 5001
RUN sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf
RUN rm -rf /user/share/nginx/html/*
COPY --from=node-build /home/ui-build/dist /usr/share/nginx/html
CMD ["nginx","g","daemon off"]

#